//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAppDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SalesAppEntities : DbContext
    {
        public SalesAppEntities()
            : base("name=SalesAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivitiesType> ActivitiesTypes { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<PlacesDetail> PlacesDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalesAppLogInfo> SalesAppLogInfoes { get; set; }
        public virtual DbSet<UserAssignedPlace> UserAssignedPlaces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersActivity> UsersActivities { get; set; }
        public virtual DbSet<CustomForm> CustomForms { get; set; }
        public virtual DbSet<FormsAnswer> FormsAnswers { get; set; }
        public virtual DbSet<FormsQuestionField> FormsQuestionFields { get; set; }
        public virtual DbSet<InputField> InputFields { get; set; }
        public virtual DbSet<NotesActivity> NotesActivities { get; set; }
        public virtual DbSet<PhotoActivity> PhotoActivities { get; set; }
    
        public virtual ObjectResult<GetAllPlacesInfo_Result> GetAllPlacesInfo(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPlacesInfo_Result>("GetAllPlacesInfo", userIdParameter);
        }
    }
}
