//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAppDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesAppLogInfo
    {
        public int ID { get; set; }
        public int KeyId { get; set; }
        public string KeyDescription { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
