//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAppDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseActivitiesComment
    {
        public int CommentId { get; set; }
        public Nullable<int> UsersActivitiesId { get; set; }
        public string UserComment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CommentByUserId { get; set; }
    
        public virtual UsersActivity UsersActivity { get; set; }
        public virtual User User { get; set; }
    }
}
