//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAppDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersActivity()
        {
            this.UseActivitiesComments = new HashSet<UseActivitiesComment>();
        }
    
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int UserId { get; set; }
        public string PhotoUrl { get; set; }
        public string Note { get; set; }
        public string FormName { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
        public Nullable<int> AuditItems { get; set; }
        public Nullable<int> PlaceId { get; set; }
    
        public virtual ActivitiesType ActivitiesType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseActivitiesComment> UseActivitiesComments { get; set; }
    }
}
